import {lazy,Suspense,useEffect,useRef,useState,type FormEvent} from 'react';
import {ApiError,authenticate,connect,getSnapshot,getVehicleLocation,type ConnectionState,type VehicleLocationStatus} from '../api';
import type {Snapshot} from '../types';
import {ErrorBoundary} from '../components/ErrorBoundary';
import {DriverView} from '../features/dashboard/DriverView';
import {SupervisorView} from '../features/supervisor/SupervisorView';
import {OwnerView} from '../features/owner/OwnerView';
import {SensorMatrix} from '../features/sensors/SensorMatrix';
import {CameraPanels} from '../features/sensors/CameraPanels';
import {EventTimeline} from '../features/events/EventTimeline';
import {ReplayPanel} from '../features/replay/ReplayPanel';
import {Diagnostics} from '../features/diagnostics/Diagnostics';
import {SettingsView,type DiagnosticsData} from '../features/settings/SettingsView';
import {FlagshipDashboard,FleetPanel,MapScene,HardwareReadiness,RadarScope} from '../features/flagship/FlagshipDashboard';
import {Icon} from '../features/flagship/Icons';
import {useFlagship} from '../features/flagship/useFlagship';
import '../operations.css';
import {R3Evidence,EvidenceWhy} from '../features/r3/R3Evidence';
import {R3Advisory} from '../features/r3/R3Advisory';
import {readR3} from '../features/r3/contract';

const MapView=lazy(()=>import('../MapView'));
const pages=['Dashboard','Map','Sensors','Safety','Logs','Replay','Diagnostics','Settings'] as const;
type Page=typeof pages[number]; type Role='DRIVER'|'SUPERVISOR'|'OWNER / FLEET';
const pageInfo:Record<Page,{title:string;intro:string;icon:string}>={
  Dashboard:{title:'Operational overview',intro:'The right information. In the right place.',icon:'overview'},
  Map:{title:'A shared view of the route',intro:'Local maps, connected participants and honest uncertainty.',icon:'map'},
  Sensors:{title:'Your observation workspace',intro:'Understand each source before trusting its output.',icon:'sensors'},
  Safety:{title:'Every decision has a reason',intro:'Inspect the existing PV-SOE pipeline. No browser control authority.',icon:'safety'},
  Logs:{title:'The evidence timeline',intro:'Follow decisions, constraints and source events.',icon:'logs'},
  Replay:{title:'Return to the moment',intro:'Inspect recorded evidence without changing live operation.',icon:'replay'},
  Diagnostics:{title:'Know the system',intro:'Connections, versions and hardware integration readiness.',icon:'diagnostics'},
  Settings:{title:'Make the view yours',intro:'Display preferences are separate from controlled safety configuration.',icon:'settings'},
};
function route(){const hash=window.location.hash.replace(/^#\/?/,'').toLowerCase();return hash==='hmi'?{page:'Dashboard' as Page,role:'DRIVER' as Role}:{page:pages.find(p=>p.toLowerCase()===hash)??'Dashboard',role:'SUPERVISOR' as Role};}
function savedTheme(){try{return localStorage.getItem('tark.display.theme')==='day'?'day':'night';}catch{return 'night';}}
function ConnectionBadge({state}:{state:ConnectionState}){return <span className={`r2-connection ${state.toLowerCase()}`} aria-label={`Telemetry ${state}`}><i/>{state==='CONNECTED'?'Telemetry connected':state==='CONNECTING'?'Connecting':state.toLowerCase()}</span>;}
function AccessPrompt({onSubmit}:{onSubmit:(token:string)=>Promise<void>}){const [token,setToken]=useState(''),[error,setError]=useState('');async function submit(event:FormEvent){event.preventDefault();try{await onSubmit(token);}catch{setError('Access was not accepted. Confirm the deployment access token.');}}return <main className="r2-access"><div className="logo-mark">T</div><h1>Protected TARK workspace</h1><p>This deployment requires authentication. Access never grants motion authority.</p><form onSubmit={submit}><label>Access token<input type="password" value={token} onChange={e=>setToken(e.target.value)} autoComplete="current-password"/></label><button className="primary-button" type="submit">Open monitoring workspace <Icon name="arrow"/></button></form>{error&&<p role="alert">{error}</p>}</main>;}

export function OperationsApp(){
  const [page,setPage]=useState<Page>(()=>route().page),[role,setRole]=useState<Role>(()=>route().role);
  const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[connection,setConnection]=useState<ConnectionState>('CONNECTING');
  const [issue,setIssue]=useState('Connecting to TARK service…'),[accessRequired,setAccessRequired]=useState(false),[sessionVersion,setSessionVersion]=useState(0);
  const [lastTelemetry,setLastTelemetry]=useState<number|null>(null),[diagnostics,setDiagnostics]=useState<DiagnosticsData|null>(null),[vehicleLocation,setVehicleLocation]=useState<VehicleLocationStatus|null>(null);
  const [theme,setTheme]=useState(savedTheme),[mapMode,setMapMode]=useState<'course'|'geographic'>('course'),[selectedId,setSelectedId]=useState('A'),[displayMessage,setDisplayMessage]=useState('');
  const telemetryGeneration=useRef(0);
  const fleet=useFlagship(!!snapshot&&!['DEGRADED','OFFLINE','RECONNECTING'].includes(connection),sessionVersion);
  const navigate=(next:Page)=>{setPage(next);window.history.replaceState(null,'',`#/${next==='Dashboard'&&role==='DRIVER'?'hmi':next.toLowerCase()}`);};
  useEffect(()=>{const changed=()=>{const next=route();setPage(next.page);setRole(next.role);};window.addEventListener('hashchange',changed);return()=>window.removeEventListener('hashchange',changed);},[]);
  useEffect(()=>{document.documentElement.dataset.tarkTheme=theme;try{localStorage.setItem('tark.display.theme',theme);}catch{/* Storage is optional. */}},[theme]);
  useEffect(()=>{
    let active=true;const controller=new AbortController();const generation=telemetryGeneration.current;
    void getSnapshot().then(async next=>{if(!active||generation!==telemetryGeneration.current)return;setSnapshot(next);setLastTelemetry(Date.now());setIssue('');setAccessRequired(false);try{const location=await getVehicleLocation();if(active&&generation===telemetryGeneration.current)setVehicleLocation(location);}catch{/* WebSocket may still supply location. */}}).catch(error=>{if(!active||generation!==telemetryGeneration.current)return;setSnapshot(null);setVehicleLocation(null);if(error instanceof ApiError&&error.status===401)setAccessRequired(true);else setIssue('SERVER STARTING or telemetry unavailable — dashboard has no authority.');});
    fetch('/api/v1/diagnostics',{credentials:'same-origin',signal:controller.signal}).then(r=>r.ok?r.json():null).then(d=>{if(active)setDiagnostics(d);}).catch(()=>undefined);
    const stop=connect(next=>{telemetryGeneration.current+=1;setSnapshot(next);setLastTelemetry(Date.now());setIssue('');},(state,message)=>{setConnection(state);if(['DEGRADED','OFFLINE','RECONNECTING'].includes(state)){telemetryGeneration.current+=1;setSnapshot(null);setVehicleLocation(null);setIssue(message||'TELEMETRY UNAVAILABLE — previous values are not current.');}else if(message)setIssue(message);},setVehicleLocation);
    return()=>{active=false;controller.abort();telemetryGeneration.current+=1;stop();};
  },[sessionVersion]);
  const switchRole=(next:Role)=>{setRole(next);setPage('Dashboard');window.history.replaceState(null,'',next==='DRIVER'?'#/hmi':'#/dashboard');};
  async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{setDisplayMessage('Full-screen is unavailable in this browser. The workspace remains usable.');}}
  if(accessRequired)return <AccessPrompt onSubmit={async token=>{await authenticate(token);setAccessRequired(false);setSessionVersion(v=>v+1);}}/>;
  let body:JSX.Element;
  if(!snapshot)body=<div className="r2-disconnected" role="status"><span className="waiting-icon"><Icon name="connection" size={36}/></span><span className="eyebrow-r2">OBSERVATION LINK</span><h2>{connection==='CONNECTING'?'Getting the workspace ready':'Telemetry unavailable'}</h2><p>{issue}</p><p>Simulation/hardware status has not been received; no values are invented.</p><small>REST and WebSocket reconnect automatically. Previous values are not current.</small></div>;
  else switch(page){
    case 'Dashboard':body=role==='DRIVER'?<><h2>LEGACY_DECISION</h2><DriverView snapshot={snapshot}/><R3Advisory value={snapshot.r3} compact/></>:role==='OWNER / FLEET'?<><OwnerView snapshot={snapshot}/><FlagshipDashboard snapshot={snapshot} data={fleet.data} error={fleet.error} onNavigate={navigate}/></>:<FlagshipDashboard snapshot={snapshot} data={fleet.data} error={fleet.error} onNavigate={navigate}/>;break;
case 'Map':body=<><div className="r2-segmented" aria-label="Map view"><button aria-pressed={mapMode==='course'} onClick={()=>setMapMode('course')}>Offline demonstration course</button><button aria-pressed={mapMode==='geographic'} onClick={()=>setMapMode('geographic')}>Geographic context</button></div>{mapMode==='course'?<><div className="overview-main full-map"><section className="r2-card course-card"><MapScene data={fleet.data} error={fleet.error} selectedId={selectedId} onSelect={setSelectedId}/></section>{fleet.data&&<FleetPanel data={fleet.data} selectedId={selectedId} onSelect={setSelectedId}/>}</div><div className="r2-callout"><Icon name="map"/><p><b>Map context is not motion authority.</b> This synthetic course is not surveyed, route-approved or spatially synchronized with the core radar simulation. Geographic context remains available separately.</p></div></>:<ErrorBoundary label="Map service unavailable"><Suspense fallback={<div className="r2-map-empty">Loading geographic map…</div>}><MapView snapshot={snapshot} vehicleLocation={vehicleLocation} mapConfig={diagnostics?.map}/></Suspense></ErrorBoundary>}</>;break;
    case 'Sensors':body=<><div className="r2-callout"><Icon name="sensors"/><p><b>Flagship profile · hardware pending.</b> Old BNO055 / MLX90640 / LD2450 interfaces do not verify BNO085 / Lepton / TI radar integration.</p></div><ErrorBoundary label="Camera panel unavailable"><CameraPanels browserPreviewEnabled={diagnostics?.capabilities?.browser_camera_preview===true}/></ErrorBoundary><div className="sensor-observation-grid"><RadarScope snapshot={snapshot}/><section className="r2-card"><div className="card-heading"><h2>Current software sources</h2><span className="small-badge">{snapshot.mode}</span></div><div className="source-list">{snapshot.sensors.map(s=><div key={s.device_id}><span><b>{s.device_id}</b><small>{s.source_mode}</small></span><span>{s.state}<small>{s.age_ms===null?'Age unavailable':`${Math.round(s.age_ms)} ms`}</small></span></div>)}</div></section></div><HardwareReadiness data={fleet.data}/><details className="r2-details"><summary>Earlier prototype interface inventory</summary><p>Legacy software reference only. Not the flagship's released GPIOs or device drivers.</p><SensorMatrix snapshot={snapshot}/></details></>;break;
    case 'Safety':body=<><div className="r2-callout"><Icon name="safety"/><p><b>Research advisory only.</b> No automatic braking, steering or propulsion. Parameters are not field validated. UNKNOWN is never converted into a normal state by the browser.</p></div><R3Advisory value={snapshot.r3}/><h2>LEGACY_DECISION</h2><SupervisorView snapshot={snapshot}/><EvidenceWhy value={snapshot.r3}/></>;break;
    case 'Logs':body=<ErrorBoundary label="Event log unavailable"><EventTimeline snapshot={snapshot}/></ErrorBoundary>;break;
    case 'Replay':body=<ErrorBoundary label="Replay unavailable"><ReplayPanel recordingControlsAvailable={diagnostics!==null&&diagnostics.deployment_environment!=='public_demo'}/></ErrorBoundary>;break;
    case 'Diagnostics':body=<><Diagnostics diagnostics={diagnostics}/><R3Advisory value={snapshot.r3}/><R3Evidence value={snapshot.r3} engineeringWrites={diagnostics!==null&&diagnostics.deployment_environment!=='public_demo'}/><HardwareReadiness data={fleet.data}/></>;break;
    case 'Settings':body=<><section className="r2-card display-settings"><h2>Display appearance</h2><p>Choose the contrast that suits your environment.</p><div className="r2-segmented"><button aria-pressed={theme==='night'} onClick={()=>setTheme('night')}><Icon name="moon"/> Night operations</button><button aria-pressed={theme==='day'} onClick={()=>setTheme('day')}><Icon name="sun"/> Daylight</button></div></section><SettingsView diagnostics={diagnostics} connection={connection} lastTelemetry={lastTelemetry}/></>;break;
  }
  return <div className={`r2-shell ${role==='DRIVER'?'driver-mode':''}`}><a className="skip-link" href="#workspace" onClick={event=>{event.preventDefault();document.getElementById('workspace')?.focus();}}> Skip to workspace</a><aside className="r2-sidebar"><a className="r2-brand" href="#/dashboard" aria-label="TARK overview"><span className="logo-mark">T</span><span>TARK<small>FIELD INTELLIGENCE</small></span></a><div className="workspace-label"><span className="workspace-avatar">R2</span><span>Flagship workspace<small>SIH26007 · Research</small></span></div><span className="nav-heading">WORKSPACE</span><nav aria-label="Primary navigation">{pages.map(p=><button key={p} aria-current={page===p?'page':undefined} aria-label={p} className={page===p?'active':''} onClick={()=>navigate(p)}><Icon name={pageInfo[p].icon}/><span>{p==='Dashboard'?'Overview':p==='Logs'?'Events':p}</span>{page===p&&<span className="nav-active-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="research-note"><Icon name="safety"/><b>Built for evidence.</b><p>Research prototype.<br/>No browser motion authority.</p></div><span className="sidebar-version">TARK R2 <span>LOCAL FIRST</span></span></div></aside>
    <div className="r2-stage"><header className="r2-topbar"><div className="breadcrumb">Workspace <span>/</span><b>{page==='Dashboard'?'Overview':page}</b></div><div className="topbar-tools"><ConnectionBadge state={connection}/><button className="icon-button" aria-label={theme==='night'?'Switch to daylight':'Switch to night mode'} onClick={()=>setTheme(theme==='night'?'day':'night')}><Icon name={theme==='night'?'sun':'moon'}/></button><button className="icon-button" aria-label="Toggle full screen" onClick={()=>void fullscreen()}><Icon name="expand"/></button><span className="operator-avatar" aria-label="Research operator">TK</span></div></header>
    <div className="r2-mode-strip"><span className="source-mode"><i/>{page==='Replay'?'REPLAY VIEW · ':''}{snapshot?.mode??'SOURCE UNKNOWN'}{snapshot?.r3!==undefined?` · R3 ${readR3(snapshot.r3)?.source_mode??'INVALID / UNAVAILABLE'}`:''}</span><span>Monitoring only</span><span>No automatic braking</span><span className="traction-label">TRACTION DISABLED — PHASE 1</span></div><main id="workspace" className="r2-workspace" tabIndex={-1}><div className="r2-page-heading"><div><span className="eyebrow-r2">{role==='DRIVER'?'DRIVER WORKSPACE':'TARK OPERATIONS'}</span><h1>{role==='DRIVER'&&page==='Dashboard'?'Focus on what matters.':pageInfo[page].title}</h1><p>{pageInfo[page].intro}</p></div><label className="role-picker"><span>View as</span><select aria-label="Role" value={role} onChange={e=>switchRole(e.target.value as Role)}><option value="SUPERVISOR">Control room</option><option value="DRIVER">Driver</option><option value="OWNER / FLEET">Owner / fleet</option></select></label></div>{displayMessage&&<p role="status" className="r2-callout">{displayMessage}</p>}<ErrorBoundary label="Workspace unavailable">{body}</ErrorBoundary><footer className="r2-footer"><span>TARK SIH26007 · Student research demonstrator</span><span>Physical validation pending · {snapshot?.traction??'No command authority'}</span></footer></main></div></div>;
}
