import {useEffect,useRef,useState} from 'react';
import {getVehicleCameraStatus,type CameraStatus} from '../../api';

const unavailable:CameraStatus={source_id:'vehicle_rgb_camera',source_mode:'NOT_CONNECTED_PHASE_2',state:'NOT_CONNECTED',timestamp_ns:null,age_ms:null,resolution:null,frame_rate_fps:null,reason:'CAMERA NOT CONNECTED',stream_url:null,stream_transport:'PENDING_PI_UVC_INTEGRATION',hardware_claim:'NOT_CONNECTED'};

function CameraMetadata({camera}:{camera:CameraStatus}){const stream=camera.state==='ONLINE'&&!!camera.stream_url;const live=camera.source_mode==='PI_UVC'&&stream;const label=camera.source_mode==='PI_UVC'?'PI UVC CAMERA':camera.source_mode==='SIMULATION'?'SIMULATION CAMERA':camera.source_mode==='REPLAY'?'REPLAY CAMERA':'PI UVC CAMERA';return <article className="vehicle-camera"><b>VEHICLE RGB CAMERA</b><span className={`camera-state ${camera.state.toLowerCase()}`}>{live?'● LIVE VEHICLE CAMERA':camera.state==='NOT_CONNECTED'?'CAMERA NOT CONNECTED':camera.source_mode==='SIMULATION'?'SIMULATION CAMERA':camera.state}</span>{stream?<img className="vehicle-camera-video" src={camera.stream_url!} alt={live?'Live vehicle RGB camera stream':'Simulated or replay camera stream'}/>:<div className="camera-empty" role="status">{camera.reason}</div>}<small>Source: {label}</small><small>Resolution: {camera.resolution??'UNAVAILABLE'} · FPS: {camera.frame_rate_fps??'UNAVAILABLE'}</small><small>Freshness: {camera.age_ms===null?'UNAVAILABLE':`${Math.round(camera.age_ms)} ms`} · Pixel format: {camera.pixel_format??'UNAVAILABLE'}</small><small>Sequence: {camera.sequence??'UNAVAILABLE'} · Dropped: {camera.dropped_frames??0} · Hardware: {camera.hardware_claim}</small></article>}

export function CameraPanels({browserPreviewEnabled}:{browserPreviewEnabled:boolean}){
  const video=useRef<HTMLVideoElement>(null); const stream=useRef<MediaStream|null>(null); const [state,setState]=useState('DEVELOPMENT BROWSER CAMERA NOT STARTED'); const [active,setActive]=useState(false); const [camera,setCamera]=useState<CameraStatus>(unavailable);
  useEffect(()=>{let cancelled=false;void getVehicleCameraStatus().then(value=>{if(!cancelled)setCamera(value);}).catch(()=>{if(!cancelled)setCamera(unavailable);});return()=>{cancelled=true;stream.current?.getTracks().forEach(track=>track.stop());};},[]);
  const stop=()=>{stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;if(video.current)video.current.srcObject=null;setActive(false);setState('DEVELOPMENT BROWSER CAMERA STOPPED');};
  const start=async()=>{if(!browserPreviewEnabled){setState('DEVELOPMENT BROWSER CAMERA DISABLED BY SERVER CONFIGURATION');return;}if(!navigator.mediaDevices?.getUserMedia){setState('DEVELOPMENT BROWSER CAMERA UNAVAILABLE');return;}try{const next=await navigator.mediaDevices.getUserMedia({video:true,audio:false});stream.current=next;setActive(true);setState('DEVELOPMENT BROWSER CAMERA ACTIVE — NOT VEHICLE CAMERA');queueMicrotask(()=>{if(video.current)video.current.srcObject=next;});}catch{setState('BROWSER CAMERA PERMISSION DENIED OR UNAVAILABLE');}};
  return <section className="camera-panels panel"><h2>Camera and thermal observation <em>MONITORING ONLY</em></h2><div><CameraMetadata camera={camera}/><article><b>THERMAL CAMERA</b><small>MLX90640 software interface: READY</small><small>Status: NOT CONNECTED · Frame: UNAVAILABLE</small><small>No thermal matrix is rendered until a real or explicitly simulated frame exists.</small></article><article><b>DEVELOPMENT BROWSER CAMERA</b><small>Development-only local preview. Never uploaded or sent to TARK. NOT VEHICLE CAMERA.</small><div className="camera-controls"><button type="button" onClick={start}>Start local preview</button><button type="button" onClick={stop}>Stop preview</button></div><small aria-live="polite">{state}</small>{active&&<video ref={video} className="browser-camera-video" muted autoPlay playsInline aria-label="Development browser camera preview"/>}</article></div></section>;
}
