#include <assert.h>
#include <stdio.h>
#include "../main/protocol/tark_protocol.h"
#include "../main/command/command_supervisor.h"
#include "../main/hardware/motor_driver.h"
#include "../main/hardware/encoder.h"
#include "../main/safety/watchdog.h"
#include "../main/protocol/command_payload.h"
#include "protocol_vectors.h"
static void assert_vector(const uint8_t *wire,size_t wire_n,uint8_t type,uint64_t sequence,uint64_t timestamp){uint8_t scratch[640];tark_frame_t frame;assert(tark_decode_frame(wire,wire_n,scratch,sizeof(scratch),&frame)==TARK_OK);assert(frame.type==type&&frame.sequence==sequence&&frame.timestamp_ns==timestamp);}
int main(void){const uint8_t known[]="123456789";uint8_t raw[640],encoded[640];size_t raw_n=sizeof(raw),encoded_n=sizeof(encoded);assert(tark_crc32c(known,9)==0xe3069283u);assert_vector(VECTOR_COMMAND_FRAME,VECTOR_COMMAND_FRAME_SIZE,TARK_COMMAND,1,1000000000ull);assert_vector(VECTOR_ACK_FRAME,VECTOR_ACK_FRAME_SIZE,TARK_ACK,1,1000000000ull);assert_vector(VECTOR_NACK_FRAME,VECTOR_NACK_FRAME_SIZE,TARK_NACK,2,1000000001ull);assert_vector(VECTOR_STATUS_FRAME,VECTOR_STATUS_FRAME_SIZE,TARK_STATUS,42,123456789ull);assert_vector(VECTOR_HEARTBEAT_BOUNDARY_FRAME,VECTOR_HEARTBEAT_BOUNDARY_FRAME_SIZE,TARK_HEARTBEAT,UINT32_MAX,UINT64_MAX);assert(tark_cobs_decode(VECTOR_STATUS_FRAME+1,VECTOR_STATUS_FRAME_SIZE-2,raw,&raw_n)==TARK_OK);assert(tark_cobs_encode(raw,raw_n,encoded,&encoded_n)==TARK_OK);assert(encoded_n==VECTOR_STATUS_FRAME_SIZE-2);for(size_t i=0;i<encoded_n;i++)assert(encoded[i]==VECTOR_STATUS_FRAME[i+1]);const uint8_t zeros[]={0,0,1,0};raw_n=sizeof(raw);assert(tark_cobs_decode((const uint8_t[]){1,1,2,1},4,raw,&raw_n)==TARK_OK);encoded_n=sizeof(encoded);assert(tark_cobs_encode(zeros,sizeof(zeros),encoded,&encoded_n)==TARK_OK);assert(tark_cobs_decode((const uint8_t[]){0},1,raw,&raw_n)==TARK_BAD_FRAME);tark_command_payload_t payload;assert(tark_validate_command_cbor(VECTOR_COMMAND_CBOR,VECTOR_COMMAND_CBOR_SIZE,1,1000000000ull,1000000000ull,"x",&payload));assert(payload.valid&&payload.left_command==0.0f&&payload.right_command==0.0f);assert(!tark_validate_command_cbor(VECTOR_COMMAND_CBOR,VECTOR_COMMAND_CBOR_SIZE,2,1000000000ull,1000000000ull,"x",&payload));command_supervisor_t s;command_supervisor_init(&s);assert(s.phase1_output_disabled);assert(command_supervisor_accept(&s,1,100,200,true)==NACK_NONE);assert(command_supervisor_accept(&s,1,101,200,true)==NACK_DUPLICATE_SEQUENCE);assert(command_supervisor_accept(&s,2,201,200,true)==NACK_EXPIRED_COMMAND);command_supervisor_force_safe_stop(&s,NACK_HEARTBEAT_TIMEOUT);assert(s.phase1_output_disabled);assert(command_supervisor_heartbeat_expired(&s,701,500));motor_driver_t motor;motor_driver_init(&motor);assert(!motor_driver_apply_bounded(&motor,2.0f,-2.0f));assert(motor.applied_left==0.0f&&motor.applied_right==0.0f);puts("host protocol tests PASS");return 0;}
