#include "command_payload.h"
#include <math.h>
#include <string.h>

typedef struct { const uint8_t *p,*end; } reader_t;
static bool head(reader_t*r,uint8_t *major,uint64_t *value){if(r->p>=r->end)return false;uint8_t b=*r->p++;*major=b>>5;uint8_t a=b&31;if(a<24){*value=a;return true;}size_t n=a==24?1:a==25?2:a==26?4:a==27?8:0;if(!n||(size_t)(r->end-r->p)<n)return false;uint64_t x=0;for(size_t i=0;i<n;i++)x=(x<<8)|*r->p++;*value=x;return true;}
static bool text(reader_t*r,char *out,size_t cap){uint8_t m;uint64_t n;if(!head(r,&m,&n)||m!=3||n>=cap||(size_t)(r->end-r->p)<n)return false;memcpy(out,r->p,(size_t)n);out[n]=0;r->p+=n;return true;}
static bool number(reader_t*r,float*out){if(r->p>=r->end)return false;uint8_t b=*r->p;if((b>>5)==0){uint8_t m;uint64_t n;if(!head(r,&m,&n))return false;*out=(float)n;return isfinite(*out);}if(b==0xf9){if(r->end-r->p<3)return false;r->p++;uint16_t h=((uint16_t)r->p[0]<<8)|r->p[1];r->p+=2;uint32_t sign=(uint32_t)(h>>15),exp=(h>>10)&31,frac=h&1023;float v;if(exp==0)v=frac?ldexpf((float)frac,-24):0.0f;else if(exp==31)return false;else v=ldexpf(1.0f+(float)frac/1024.0f,(int)exp-15);*out=sign?-v:v;return true;}return false;}
static bool u64(reader_t*r,uint64_t*out){uint8_t m;return head(r,&m,out)&&m==0;}
static bool skip(reader_t*r){uint8_t m;uint64_t n;if(!head(r,&m,&n))return false;if(m==0||m==1||m==7)return true;if((m==2||m==3)){if((size_t)(r->end-r->p)<n)return false;r->p+=n;return true;}return false;}
bool tark_validate_command_cbor(const uint8_t*data,size_t length,uint64_t sequence,uint64_t timestamp,uint64_t now,const char*hash,tark_command_payload_t*out){reader_t r={data,data+length};uint8_t m;uint64_t count;if(!out||!hash||!head(&r,&m,&count)||m!=5||count>24)return false;bool seen_seq=false,seen_ts=false,seen_until=false,seen_speed=false,seen_left=false,seen_right=false,seen_hash=false,seen_state=false,seen_reason=false,seen_hb=false,seen_ver=false;memset(out,0,sizeof(*out));for(uint64_t i=0;i<count;i++){char key[32];if(!text(&r,key,sizeof(key)))return false;if(!strcmp(key,"sequence")){uint64_t x;if(!u64(&r,&x)||x!=sequence)return false;seen_seq=true;}else if(!strcmp(key,"timestamp_ns")){uint64_t x;if(!u64(&r,&x)||x!=timestamp)return false;seen_ts=true;}else if(!strcmp(key,"valid_until_ns")){if(!u64(&r,&out->valid_until_ns)||out->valid_until_ns<=now)return false;seen_until=true;}else if(!strcmp(key,"permitted_speed_mps")){if(!number(&r,&out->permitted_speed_mps)||out->permitted_speed_mps<0)return false;seen_speed=true;}else if(!strcmp(key,"left_command")){if(!number(&r,&out->left_command)||fabsf(out->left_command)>1)return false;seen_left=true;}else if(!strcmp(key,"right_command")){if(!number(&r,&out->right_command)||fabsf(out->right_command)>1)return false;seen_right=true;}else if(!strcmp(key,"heartbeat")){uint64_t x;if(!u64(&r,&x)||x>UINT32_MAX)return false;out->heartbeat=(uint32_t)x;seen_hb=true;}else if(!strcmp(key,"configuration_hash")){char x[128];if(!text(&r,x,sizeof(x))||strcmp(x,hash))return false;seen_hash=true;}else if(!strcmp(key,"protocol_version")){uint64_t x;if(!u64(&r,&x)||x!=1)return false;seen_ver=true;}else if(!strcmp(key,"state")){char x[16];if(!text(&r,x,sizeof(x))||(strcmp(x,"NORMAL")&&strcmp(x,"WARN")&&strcmp(x,"RESTRICT")&&strcmp(x,"UNKNOWN")&&strcmp(x,"STOP")))return false;seen_state=true;}else if(!strcmp(key,"reason_code")){char x[32];if(!text(&r,x,sizeof(x)))return false;seen_reason=true;}else if(!skip(&r))return false;}out->valid=seen_seq&&seen_ts&&seen_until&&seen_speed&&seen_left&&seen_right&&seen_hash&&seen_state&&seen_reason&&seen_hb&&seen_ver&&r.p==r.end;return out->valid;}
bool tark_validate_heartbeat_cbor(const uint8_t*data,size_t length,const char*hash){reader_t r={data,data+length};uint8_t m;uint64_t count;if(!hash||!head(&r,&m,&count)||m!=5||count!=2)return false;bool seen_hash=false,seen_ver=false;for(uint64_t i=0;i<count;i++){char key[32];if(!text(&r,key,sizeof(key)))return false;if(!strcmp(key,"configuration_hash")){char x[128];if(!text(&r,x,sizeof(x))||strcmp(x,hash))return false;seen_hash=true;}else if(!strcmp(key,"protocol_version")){uint64_t x;if(!u64(&r,&x)||x!=1)return false;seen_ver=true;}else return false;}return seen_hash&&seen_ver&&r.p==r.end;}
int tark_command_configuration_state(const uint8_t*data,size_t length,const char*hash){reader_t r={data,data+length};uint8_t m;uint64_t count;if(!hash||!head(&r,&m,&count)||m!=5||count>24)return 0;for(uint64_t i=0;i<count;i++){char key[32];if(!text(&r,key,sizeof(key)))return 0;if(!strcmp(key,"configuration_hash")){char x[128];if(!text(&r,x,sizeof(x)))return 0;return strcmp(x,hash)?2:1;}if(!skip(&r))return 0;}return 0;}
