#include "response.h"
#include <string.h>

typedef struct {uint8_t *p,*end;bool ok;} writer_t;
static void byte(writer_t*w,uint8_t x){if(w->p>=w->end){w->ok=false;return;}*w->p++=x;}
static void text(writer_t*w,const char*s){size_t n=strlen(s);if(n>23){byte(w,0x78);byte(w,(uint8_t)n);}else byte(w,(uint8_t)(0x60u+n));for(size_t i=0;i<n;i++)byte(w,(uint8_t)s[i]);}
static void fzero(writer_t*w){byte(w,0xf9);byte(w,0);byte(w,0);}
static bool frame(uint8_t type,uint64_t sequence,uint64_t timestamp,const uint8_t*payload,size_t payload_n,uint8_t*out,size_t*out_n){uint8_t raw[TARK_MAX_FRAME];if(!out||!out_n||payload_n>TARK_MAX_PAYLOAD||*out_n<TARK_MAX_FRAME)return false;raw[0]=0x54;raw[1]=0x4b;raw[2]=1;raw[3]=type;raw[4]=(uint8_t)(payload_n>>24);raw[5]=(uint8_t)(payload_n>>16);raw[6]=(uint8_t)(payload_n>>8);raw[7]=(uint8_t)payload_n;for(int i=0;i<8;i++)raw[8+i]=(uint8_t)(sequence>>(56-8*i));for(int i=0;i<8;i++)raw[16+i]=(uint8_t)(timestamp>>(56-8*i));memcpy(raw+24,payload,payload_n);uint32_t crc=tark_crc32c(raw,24+payload_n);raw[24+payload_n]=(uint8_t)(crc>>24);raw[25+payload_n]=(uint8_t)(crc>>16);raw[26+payload_n]=(uint8_t)(crc>>8);raw[27+payload_n]=(uint8_t)crc;size_t encoded=*out_n-2;tark_protocol_result_t result=tark_cobs_encode(raw,28+payload_n,out+1,&encoded);if(result!=TARK_OK||encoded+2>*out_n)return false;out[0]=0;out[encoded+1]=0;*out_n=encoded+2;return true;}
static bool response(uint8_t type,uint64_t sequence,uint64_t timestamp,bool accepted,const char*reason,uint8_t*out,size_t*out_n){uint8_t payload[TARK_MAX_PAYLOAD];writer_t w={payload,payload+sizeof(payload),true};byte(&w,0xa6);text(&w,"reason");text(&w,reason);text(&w,"accepted");byte(&w,accepted?0xf5:0xf4);text(&w,"source_mode");text(&w,"REAL");text(&w,"applied_left");fzero(&w);text(&w,"output_state");text(&w,"DISABLED_PHASE_1");text(&w,"applied_right");fzero(&w);return w.ok&&frame(type,sequence,timestamp,payload,(size_t)(w.p-payload),out,out_n);}
bool tark_build_ack(uint64_t sequence,uint64_t timestamp,const char*reason,uint8_t*out,size_t*out_n){return response(TARK_ACK,sequence,timestamp,true,reason,out,out_n);}
bool tark_build_nack(uint64_t sequence,uint64_t timestamp,const char*reason,uint8_t*out,size_t*out_n){return response(TARK_NACK,sequence,timestamp,false,reason,out,out_n);}
bool tark_build_status(uint64_t sequence,uint64_t timestamp,const char*reason,uint8_t*out,size_t*out_n){uint8_t payload[TARK_MAX_PAYLOAD];writer_t w={payload,payload+sizeof(payload),true};byte(&w,0xa2);text(&w,"reason");text(&w,reason);text(&w,"output_state");text(&w,"DISABLED_PHASE_1");return w.ok&&frame(TARK_STATUS,sequence,timestamp,payload,(size_t)(w.p-payload),out,out_n);}
