#include "service.h"
#include "command_payload.h"
#include "response.h"
#include "tark_protocol.h"
#include <string.h>
static void send_frame(tark_protocol_service_t*s,bool ok,uint64_t sequence,uint64_t timestamp,const char*reason){uint8_t out[TARK_MAX_FRAME];size_t n=sizeof(out);if((ok?tark_build_ack(sequence,timestamp,reason,out,&n):tark_build_nack(sequence,timestamp,reason,out,&n))&&s->tx)s->tx(out,n,s->tx_context);}
static void process(tark_protocol_service_t*s,uint64_t now){uint8_t framed[TARK_MAX_FRAME],scratch[TARK_MAX_FRAME];tark_frame_t frame;if(s->encoded_length+2>TARK_MAX_FRAME){s->frames_invalid++;return;}framed[0]=0;memcpy(framed+1,s->encoded,s->encoded_length);framed[s->encoded_length+1]=0;tark_protocol_result_t result=tark_decode_frame(framed,s->encoded_length+2,scratch,sizeof(scratch),&frame);if(result!=TARK_OK){s->frames_invalid++;return;}if(frame.type==TARK_COMMAND){tark_command_payload_t command;if(frame.sequence>UINT32_MAX||!tark_validate_command_cbor(frame.payload,frame.payload_length,frame.sequence,frame.timestamp_ns,now,s->configuration_hash,&command)){s->frames_invalid++;send_frame(s,false,frame.sequence,frame.timestamp_ns,tark_command_configuration_state(frame.payload,frame.payload_length,s->configuration_hash)==2?"CONFIGURATION_MISMATCH":"INVALID_PAYLOAD");return;}command_reject_t rejected=command_supervisor_accept(&s->supervisor,(uint32_t)frame.sequence,now,command.valid_until_ns,true);if(rejected!=NACK_NONE){s->frames_invalid++;send_frame(s,false,frame.sequence,frame.timestamp_ns,s->supervisor.last_rejection);return;}s->frames_valid++;send_frame(s,true,frame.sequence,frame.timestamp_ns,"COMMAND_ACCEPTED_DISABLED_PHASE_1");return;}if(frame.type==TARK_HEARTBEAT){if(!tark_validate_heartbeat_cbor(frame.payload,frame.payload_length,s->configuration_hash)){s->frames_invalid++;send_frame(s,false,frame.sequence,frame.timestamp_ns,"INVALID_PAYLOAD");return;}s->supervisor.heartbeat_ns=now;s->frames_valid++;send_frame(s,true,frame.sequence,frame.timestamp_ns,"HEARTBEAT_ACCEPTED");return;}s->frames_invalid++;send_frame(s,false,frame.sequence,frame.timestamp_ns,"NOT_ENABLED");}
void tark_protocol_service_init(tark_protocol_service_t*s,const char*hash,tark_tx_callback_t tx,void*context){memset(s,0,sizeof(*s));command_supervisor_init(&s->supervisor);s->configuration_hash=hash;s->tx=tx;s->tx_context=context;}
void tark_protocol_service_receive(tark_protocol_service_t*s,const uint8_t*bytes,size_t length,uint64_t now){if(!s||!bytes)return;for(size_t i=0;i<length;i++){uint8_t b=bytes[i];if(b==0){if(s->in_frame&&s->encoded_length){process(s,now);s->encoded_length=0;s->in_frame=true;}else{s->in_frame=true;s->encoded_length=0;}continue;}if(!s->in_frame)continue;if(s->encoded_length>=sizeof(s->encoded)){s->encoded_length=0;s->in_frame=false;s->frames_invalid++;continue;}s->encoded[s->encoded_length++]=b;}}
void tark_protocol_service_status(tark_protocol_service_t*s,uint64_t sequence,uint64_t now){uint8_t out[TARK_MAX_FRAME];size_t n=sizeof(out);if(s&&tark_build_status(sequence,now,s->supervisor.last_rejection,out,&n)&&s->tx)s->tx(out,n,s->tx_context);}
