#include "tark_protocol.h"
#include <string.h>
static uint16_t be16(const uint8_t *p){return ((uint16_t)p[0]<<8)|p[1];}
static uint32_t be32(const uint8_t *p){return ((uint32_t)p[0]<<24)|((uint32_t)p[1]<<16)|((uint32_t)p[2]<<8)|p[3];}
static uint64_t be64(const uint8_t *p){uint64_t x=0;for(int i=0;i<8;i++)x=(x<<8)|p[i];return x;}
uint32_t tark_crc32c(const uint8_t *data,size_t size){uint32_t c=0xffffffffu;for(size_t i=0;i<size;i++){c^=data[i];for(int b=0;b<8;b++)c=(c&1)?(c>>1)^0x82f63b78u:c>>1;}return ~c;}
tark_protocol_result_t tark_cobs_decode(const uint8_t *in,size_t n,uint8_t*out,size_t*on){size_t i=0,o=0;if(!n)return TARK_BAD_FRAME;while(i<n){uint8_t code=in[i++];if(code==0||i+code-1>n)return TARK_BAD_FRAME;for(uint8_t j=1;j<code;j++){if(o>=*on)return TARK_OVERSIZED;if(in[i]==0)return TARK_BAD_FRAME;out[o++]=in[i++];}if(code<255&&i<n){if(o>=*on)return TARK_OVERSIZED;out[o++]=0;}}*on=o;return TARK_OK;}
tark_protocol_result_t tark_cobs_encode(const uint8_t *in,size_t n,uint8_t*out,size_t*on){size_t oi=1,code_index=0;uint8_t code=1;if(*on<1)return TARK_OVERSIZED;for(size_t i=0;i<n;i++){if(in[i]==0){if(code_index>=*on||oi>=*on)return TARK_OVERSIZED;out[code_index]=code;code_index=oi++;code=1;}else{if(oi>=*on)return TARK_OVERSIZED;out[oi++]=in[i];if(++code==0xff){out[code_index]=code;if(oi>=*on)return TARK_OVERSIZED;code_index=oi++;code=1;}}}if(code_index>=*on)return TARK_OVERSIZED;out[code_index]=code;*on=oi;return TARK_OK;}
tark_protocol_result_t tark_decode_frame(const uint8_t *f,size_t n,uint8_t*s,size_t sn,tark_frame_t*out){if(n<3||n>TARK_MAX_FRAME||f[0]!=0||f[n-1]!=0)return TARK_BAD_FRAME;size_t dn=sn; tark_protocol_result_t r=tark_cobs_decode(f+1,n-2,s,&dn);if(r)return r;/* 24-byte envelope + payload + 4-byte CRC */if(dn<28)return TARK_BAD_LENGTH;uint32_t supplied=be32(s+dn-4);if(tark_crc32c(s,dn-4)!=supplied)return TARK_BAD_CRC;if(be16(s)!=TARK_MAGIC)return TARK_BAD_MAGIC;if(s[2]!=TARK_PROTOCOL_VERSION)return TARK_BAD_VERSION;if(s[3]<TARK_COMMAND||s[3]>TARK_OBSERVATION)return TARK_UNKNOWN_TYPE;uint32_t plen=be32(s+4);if(plen>TARK_MAX_PAYLOAD||plen!=dn-28||be64(s+8)>UINT32_MAX)return TARK_BAD_LENGTH;out->type=s[3];out->sequence=be64(s+8);out->timestamp_ns=be64(s+16);out->payload_length=plen;out->payload=s+24;return TARK_OK;}
