import {lazy,Suspense,useState} from 'react';
import type {Snapshot,State} from '../../types';
import {StateBadge} from '../../components/StateBadge';
import {Icon} from './Icons';
import type {FlagshipSnapshot,FlagshipParticipant} from './types';
const FlagshipMap=lazy(()=>import('./FlagshipMap'));
export const action:Record<State,string>={NORMAL:'Observe the route',WARN:'Pay attention',RESTRICT:'Reduce movement',UNKNOWN:'Guidance unavailable',STOP:'Stop and assess'};
export function readable(value:string){return value.replaceAll('_',' ').toLowerCase().replace(/^./,c=>c.toUpperCase());}
export function Value({value,unit,digits=2}:{value:number|null|undefined;unit?:string;digits?:number}){return <>{typeof value==='number'&&Number.isFinite(value)?value.toFixed(digits):'—'}{unit&&<small> {unit}</small>}</>;}

export function RadarScope({snapshot}:{snapshot:Snapshot}){
  const valid=snapshot.tracks.filter(t=>Number.isFinite(t.x_m)&&Number.isFinite(t.y_m));
  const shown=valid.slice(0,50);
  const limit=Math.ceil(Math.max(5,...shown.map(t=>Math.max(Math.abs(t.x_m),Math.abs(t.y_m))))/5)*5;
  return <section className="r2-card radar-card"><div className="card-heading"><h2><Icon name="radar"/> Radar tracks</h2><span className="small-badge">{snapshot.mode}</span></div><div className="radar-plot"><svg viewBox="0 0 360 300" role="img" aria-label={`${shown.length} displayed local radar targets. X forward, Y left. Full local plane, not georeferenced.`}><g className="radar-grid-lines"><path d="M180 35V265 M65 150H295"/>{[36,73,110].map(r=><circle key={r} cx="180" cy="150" r={r}/>)}<rect x="70" y="40" width="220" height="220"/></g><text x="180" y="20" textAnchor="middle">FORWARD +X</text><text x="10" y="145">+Y</text><text x="180" y="286" textAnchor="middle">REAR −X · ±{limit} m per axis</text><path d="m180 141 6 12h-12z" className="radar-origin-mark"/>{shown.map((t,i)=>{const x=180-t.y_m/limit*110,y=150-t.x_m/limit*110;return <g key={t.track_id} data-testid="radar-target"><circle cx={x} cy={y} r="5" className="radar-track"/><text x={x>260?x-10:x+9} y={y-8} textAnchor={x>260?'end':'start'}>T{i+1}</text></g>;})}</svg></div><div className="radar-foot"><span>{shown.length} displayed / {snapshot.tracks.length} received</span><span>Local frame only</span></div>{shown.length!==snapshot.tracks.length&&<p className="subtle">Display limited to 50 finite targets; omitted observations are not treated as clear space.</p>}</section>;
}

export function participantFresh(p:FlagshipParticipant){return p.position!==null&&['SIMULATED','ONLINE'].includes(p.state)&&p.age_ms!==null&&p.age_ms>=0&&p.age_ms<=3000;}

function Participant({participant,selected,onSelect}:{participant:FlagshipParticipant;selected:boolean;onSelect:()=>void}){return <button className={`participant-row ${selected?'selected':''}`} onClick={onSelect} aria-pressed={selected}><span className={`vehicle-avatar ${participant.role==='LOCATION_ONLY'?'secondary':''}`}><Icon name={participant.role==='LOCATION_ONLY'?'pin':'truck'}/></span><span className="participant-name"><b>{participant.name}</b><small>{participant.role==='LOCATION_ONLY'?'Location-only node':'Instrumented cart'}</small></span><span className="participant-source"><b>{participant.source_mode}</b><small>{participantFresh(participant)?`${Math.round(participant.age_ms!)} ms`:participant.position?'Last known':'No position'}</small></span></button>;}

export function FleetPanel({data,selectedId,onSelect}:{data:FlagshipSnapshot;selectedId:string;onSelect:(id:string)=>void}){
  const selected=data.participants.find(p=>p.id===selectedId)??data.participants[0];
  const fresh=selected?participantFresh(selected):false;
  const direction=fresh&&selected?(selected.role!=='LOCATION_ONLY'&&selected.heading_deg!==null?selected.heading_deg:selected.speed_mps!==null&&selected.speed_mps>0.05?selected.course_deg:null):null;
  return <section className="r2-card fleet-panel"><div className="card-heading"><h2>Participants</h2><span className="count-pill">{data.participants.filter(participantFresh).length} fresh / {data.participants.length}</span></div><div className="participant-list">{data.participants.map(p=><Participant key={p.id} participant={p} selected={p.id===selected?.id} onSelect={()=>onSelect(p.id)}/>)}</div>{selected&&<div className="participant-detail"><span className="eyebrow-r2">SELECTED PARTICIPANT</span><h3>{selected.name}</h3><dl className="detail-list"><div><dt>Source</dt><dd>{selected.source_mode}</dd></div><div><dt>Quality</dt><dd>{fresh?readable(selected.quality):selected.position?'Last known — stale':'Position unavailable'}</dd></div><div><dt>Scene speed</dt><dd><Value value={fresh?selected.speed_mps:null} unit="m/s"/></dd></div><div><dt>Position uncertainty</dt><dd><Value value={fresh?selected.accuracy_m:null} unit="m"/></dd></div><div><dt>Direction</dt><dd><Value value={direction} unit="°" digits={0}/>{direction!==null&&(selected.role==='LOCATION_ONLY'||selected.heading_deg===null)?' course':''}</dd></div></dl><p className="subtle">{selected.role==='LOCATION_ONLY'?'Node B shares location only. It has no radar, cameras or independent safety decision.':'Scene motion is presentation data, not a ground-speed measurement or input to the decision engine.'}</p></div>}<div className="panel-foot"><Icon name="connection" size={16}/> Local network · no cloud required</div></section>;
}

export function MapScene({data,error,selectedId,onSelect,compact=false}:{data:FlagshipSnapshot|null;error:string;selectedId:string;onSelect:(id:string)=>void;compact?:boolean}){return data?<Suspense fallback={<div className="r2-map-empty">Preparing the local map…</div>}><FlagshipMap scene={data.scene} participants={data.participants} selectedId={selectedId} onSelect={onSelect} compact={compact}/></Suspense>:<div className="r2-map-empty"><Icon name="map" size={34}/><h3>Course unavailable</h3><p>{error||'No fleet observations have been received.'}</p><small>No locations are invented.</small></div>;}

export function FlagshipDashboard({snapshot,data,error,onNavigate}:{snapshot:Snapshot;data:FlagshipSnapshot|null;error:string;onNavigate:(page:'Map'|'Sensors'|'Logs')=>void}){
  const [selectedId,setSelectedId]=useState('A');const d=snapshot.decision;
  return <div className="flagship-dashboard"><div className="r2-metric-grid"><article className={`r2-metric decision-${d.state.toLowerCase()}`}><div><span>Research state</span><Icon name="safety"/></div><StateBadge state={d.state}/><small>{action[d.state]??'Guidance unavailable'}</small></article><article className="r2-metric"><div><span>Permitted command</span><Icon name="diagnostics"/></div><strong><Value value={d.permitted_speed_mps} unit="m/s"/></strong><small>Phase 1 · output remains zero</small></article><article className="r2-metric"><div><span>Fleet demonstration</span><Icon name="truck"/></div><strong>{data?.participants.filter(participantFresh).length??'—'}<small> / {data?.participants.length??'—'} nodes</small></strong><small>{data?.source_mode??'AWAITING DATA'} · independent scene</small></article><article className="r2-metric"><div><span>Local radar</span><Icon name="radar"/></div><strong>{snapshot.tracks.length}<small> targets</small></strong><small>Normalized observations · {snapshot.mode}</small></article></div>
    <div className="overview-main"><section className="r2-card course-card"><div className="card-heading"><div><h2>Shared situational view</h2><p>Know where participants are. Know what is unknown.</p></div><button className="text-button" onClick={()=>onNavigate('Map')}>Open map <Icon name="arrow" size={16}/></button></div><MapScene data={data} error={error} selectedId={selectedId} onSelect={setSelectedId}/></section>{data?<FleetPanel data={data} selectedId={selectedId} onSelect={setSelectedId}/>:<section className="r2-card"><h2>Fleet connection</h2><p className="subtle">{error}</p></section>}</div>
    <div className="overview-bottom"><RadarScope snapshot={snapshot}/><section className="r2-card advisory-card"><div className="card-heading"><h2><Icon name="safety"/> Decision evidence</h2><span className="small-badge">CORE OUTPUT</span></div><h3>{action[d.state]??'Guidance unavailable'}</h3><p className="reason-label">{d.reason_code}</p><div className="envelope-values"><div><span>Effective envelope</span><b><Value value={d.D_effective_m} unit="m"/></b></div><div><span>Stopping requirement</span><b><Value value={d.stopping_requirement_m} unit="m"/></b></div></div><p className="subtle">Parameterized research output. Not a validated safe driving speed. The fleet scene does not feed these calculations.</p><div className="constraint-list">{d.active_constraints.map(v=><span key={v}>{readable(v)}</span>)}</div></section><section className="r2-card observation-card"><div className="card-heading"><h2><Icon name="camera"/> Sensor workspace</h2></div><div className="camera-illustration"><Icon name="camera" size={42}/><span>Real imagery, when available.</span><small>No camera frame is fabricated.</small></div><p className="subtle">Inspect RGB, thermal, IMU and the new hardware integration checklist in one place.</p><button className="secondary-button" onClick={()=>onNavigate('Sensors')}>Open sensors <Icon name="arrow" size={16}/></button></section></div>
    <section className="r2-card recent-events"><div className="card-heading"><h2>Latest decision events</h2><button className="text-button" onClick={()=>onNavigate('Logs')}>View timeline <Icon name="arrow" size={16}/></button></div>{snapshot.events.length?<div className="recent-list">{snapshot.events.slice(-4).reverse().map(e=><div key={e.event_id}><span className="event-line-dot"/><div><b>{readable(e.event_type)}</b><span>{readable(e.reason)}</span></div><span className="small-badge">{e.severity}</span></div>)}</div>:<p className="subtle">No events received in this observation window.</p>}</section>
  </div>;
}

export function HardwareReadiness({data}:{data:FlagshipSnapshot|null}){return <section className="r2-card hardware-readiness"><div className="card-heading"><div><h2>Hardware arrival checklist</h2><p>Selected equipment is not the same as a verified driver.</p></div><span className="small-badge">NO PHYSICAL VERIFICATION</span></div>{data?<div className="hardware-grid">{data.hardware.map(h=><article key={h.id}><Icon name={h.id.includes('camera')||h.id.includes('thermal')?'camera':'sensors'}/><h3>{h.name}</h3><span className="small-badge">{readable(h.status)}</span><dl><dt>Connection</dt><dd>{h.interface}</dd><dt>Software boundary</dt><dd>{readable(h.software_readiness)}</dd></dl><p>{h.reason}</p></article>)}</div>:<p>Readiness manifest unavailable. No connected-hardware status is assumed.</p>}<p className="subtle">Identify → configure → validate data → calibrate → review. No auto-probing, motor authority or assumption of plug-and-play compatibility.</p></section>;}
