import {useEffect,useState} from 'react';
import {getReplaySession,getReplaySessions,getReplayTimeline,startRecording,stopRecording,verifyReplay,type RecordingSession,type ReplayTimeline} from '../../api';
import {Panel} from '../../components/Panel';

function durationText(durationNs:number){return `${(durationNs/1_000_000_000).toFixed(2)} s`;}

export function ReplayPanel({recordingControlsAvailable=true}:{recordingControlsAvailable?:boolean}){
  const [position,setPosition]=useState(0),[sessions,setSessions]=useState<RecordingSession[]>([]),[selected,setSelected]=useState(''),[loaded,setLoaded]=useState<RecordingSession|null>(null),[timeline,setTimeline]=useState<ReplayTimeline|null>(null),[playing,setPlaying]=useState(false),[message,setMessage]=useState('Loading recording catalog…');
  const refresh=async()=>{try{const next=await getReplaySessions();setSessions(next);setMessage(next.length?'Select a completed observation recording.':'NOT AVAILABLE — no persisted recording exists.');}catch{setMessage('Recording catalog unavailable — dashboard remains observation only.');}};
  useEffect(()=>{void refresh();},[]);
  const items=timeline?.items??[];const maximum=Math.max(0,items.length-1);const current=items[position];const active=sessions.find(session=>session.status==='RECORDING');
  useEffect(()=>{if(!playing||items.length===0)return;const timer=window.setInterval(()=>setPosition(value=>{if(value>=maximum){setPlaying(false);setMessage('End of replay reached. Replay remains observation only.');return maximum;}return value+1;}),500);return()=>window.clearInterval(timer);},[playing,maximum,items.length]);
  const load=async()=>{if(!selected)return;setPlaying(false);try{const [session,nextTimeline]=await Promise.all([getReplaySession(selected),getReplayTimeline(selected)]);setLoaded(session);setTimeline(nextTimeline);setPosition(0);setMessage(nextTimeline.items.length?`REPLAY loaded: ${nextTimeline.items.length} normalized observation item(s), ${durationText(nextTimeline.duration_ns)}.`:'No normalized replay observations are available in this session.');}catch{setLoaded(null);setTimeline(null);setMessage('Replay load rejected: missing, corrupt, or configuration-incompatible recording.');}};
  const begin=async()=>{try{const session=await startRecording();setSelected(session.session_id);setLoaded(null);setTimeline(null);setPosition(0);setMessage('Recording started. Only received observations and computed evidence are retained.');await refresh();}catch{setMessage('Recording could not be started.');}};
  const end=async()=>{try{await stopRecording();await refresh();setMessage('Recording stopped. Select it to load an isolated REPLAY timeline.');}catch{setMessage('No active recording could be stopped.');}};
  const verify=async()=>{if(!loaded)return;try{const result=await verifyReplay(loaded.session_id);setMessage(`Replay verification: ${result.result}${result.first_divergence===null?'':' at item '+result.first_divergence}.`);}catch{setMessage('Replay verification rejected: recording is unavailable, corrupt, or configuration-incompatible.');}};
  const seek=(next:number)=>{setPlaying(false);setPosition(Math.max(0,Math.min(maximum,next)));};
  const canPlay=items.length>0&&position<maximum;
  return <Panel title="Replay" tag="REPLAY"><p><b>REPLAY</b> is isolated persisted evidence—not LIVE telemetry, not a simulator command, and never an ESP32 or traction authority.</p>{!recordingControlsAvailable&&<p className="replay-public-notice" role="status">PUBLIC DEMO: recording creation is unavailable. This page is an evidence viewer only.</p>}<label>Recording <select aria-label="Recording session" value={selected} onChange={event=>{setSelected(event.target.value);setLoaded(null);setTimeline(null);setPlaying(false);setPosition(0);}}><option value="">Select a persisted recording</option>{sessions.filter(session=>session.status!=='RECORDING').map(session=><option key={session.session_id} value={session.session_id}>{session.session_id.slice(0,8)} · {session.source_mode} · {session.record_count} item(s)</option>)}</select></label><p className="status-line">Source: {timeline?.source_mode??'NOT LOADED'} · {timeline?.state??'NO TIMELINE'}</p>{timeline&&<p>Bounds: {timeline.start_timestamp_ns??'—'} → {timeline.end_timestamp_ns??'—'} · Duration: {durationText(timeline.duration_ns)}</p>}<label>Replay position <input aria-label="Replay position" type="range" min="0" max={maximum} value={Math.min(position,maximum)} disabled={!items.length} onChange={event=>seek(Number(event.target.value))}/>{items.length?`${position+1} / ${items.length}`:'0 / 0'}</label>{current&&<div className="replay-current"><b>REPLAY ITEM {current.position+1}</b><span>{current.decision.state} · {current.decision.reason_code} · tracks: {current.track_count}</span><span>{current.event.event_type} · {current.event.severity}</span></div>}<div className="controls">{recordingControlsAvailable&&<><button onClick={()=>void begin()} disabled={!!active}>Start recording</button><button onClick={()=>void end()} disabled={!active}>Stop recording</button></>}<button onClick={()=>void load()} disabled={!selected}>Load recording</button><button onClick={()=>void verify()} disabled={!loaded}>Verify replay</button><button onClick={()=>setPlaying(true)} disabled={!canPlay||playing}>Play</button><button onClick={()=>setPlaying(false)} disabled={!playing}>Pause</button><button onClick={()=>seek(position+1)} disabled={!canPlay}>Step forward</button><button onClick={()=>seek(position-1)} disabled={!items.length||position===0}>Step backward</button><button onClick={()=>seek(0)} disabled={!items.length}>Reset</button></div><p role="status">{message}</p><small>Seek, play, pause, and steps change only this local replay viewer. LIVE telemetry, SIMULATION, and REPLAY remain separate source states.</small></Panel>;
}
